# Generated by Django 4.1 on 2022-09-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
